name:CI to Docker Hub

on:
  push:
      banches: [master]

jobs:

  build:
    runs-on:ubuntu:latest
    steps:
      -
       name: Checkout
       uses: actions/checkout@v2
      -
       name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v1
      -
       name: Cache Docker layers
       uses: action/cache@v2
       with:
        path: /tmp/.buildx-cache
        key: ${{runner.os}}-buildx-${{github.sha}}
        restore-keys: |
          ${{runner.os}}-buildx-
      -
       uses: docker/login-action@v1
       with: 
        username: ${{secrets.DOCKER_NAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
      -
       name:Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
        context: ./
        file: ./Dockerfile
        builder: ${{steps.buildx.outputs.name}}
        push: true
        tags: vladichmoiseev/last-laba:1.0
        cache-from: type=local, src=/tmp/.buildex-cache
        cache-to: type=local, dest=/tmp/.buildex-cache
      -
      name: Image digets
      run: echo ${{steps.docker_build.outputs.digets}}
